apiVersion: v1
kind: Pod
metadata:
  name: {{ name }}
  labels:
    name: {{ name }}
spec:
  containers:
{% for container in containers %}    
  - name: {{ container.name }}
    image: {{ container.image }}
    {% if container.limits %}
    resources:
      requests:
        # it's a bug that limits is an array.
        cpu: "{{ container.limits[0].cpus }}"
        memory: "{{ container.limits[0].memory }}"
    {% endif %}
{% endfor %}
