apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-{{ system.name }}
  labels:
    executor: tycho
    tycho-guid: {{ system.identifier }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: {{ pv_name }}-disk
