apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-{{ system.name }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: {{ system.name }}-disk
