apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: {{ volume_name }}
    executor: tycho
    tycho-guid: {{ system.identifier }}
  name: {{ claim_name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
