apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: {{ system.name }}
    executor: tycho
    tycho-guid: {{ system.identifier }}
  name: pvc-for-{{ system.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
