apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ system.system_name }}-global-2
  labels:
    name: {{ system.system_name }}
    tycho-guid: {{ system.identifier }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ system.system_name }}
  apiGroup: rbac.authorization.k8s.io
