version: '3.0'

services:

  jupyter:
    image: heliumdatastage/jupyter-hail:latest
    ports:
      - '8000:8000'

  spark:
    image: heliumdatastage/spark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=localhost
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'

  spark-worker:
    image: heliumdatastage/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://$app:7077
      - SPARK_WORKER_MEMORY=${cluster_worker_memory}
      - SPARK_WORKER_CORES=${cluster_worker_cores}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '${cluster_worker_cores}'
          memory: ${cluster_worker_memory}
        reservations:
          cpus: '${cluster_worker_cores}'
          memory: ${cluster_worker_memory}
      mode: replicated
      replicas: ${cluster_worker_replicas}

