version: '3.0'

services:

  jupyter:
    image: heliumdatastage/jupyter-hail:latest
    ports:
      - '8000:8000'

  spark:
    image: bitnami/spark:2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - TYCHO_NFS/spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - TYCHO_NFS/spark/jars/hail-all-spark.jar:/opt/bitnami/spark/jars/hail-all-spark.jar 
    ports:
      - '8080:8080'
      - '7077:7077'

  {% for worker in cluster.workers %}
  spark-worker-{{ loop.index }}:
    image: bitnami/spark:2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY={{ worker.memory }}G
      - SPARK_WORKER_CORES={{ worker.cores }}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - TYCHO_NFS/spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - TYCHO_NFS/spark/jars/hail-all-spark.jar:/opt/bitnami/spark/jars/hail-all-spark.jar 
  {% endfor %}
