kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tycho-api-access
rules:
- apiGroups: [""]
  resources:
    - pods
    - deployments
    - services
    - replica_sets
  verbs: ["list", "create", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tycho-api-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: tycho-api-access
  apiGroup: rbac.authorization.k8s.io
